# Generated by Django 3.1.7 on 2021-03-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ВВедите цвет', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ВВедите размер', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ВВедите стиль', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Описание', max_length=1000)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Quantity', models.PositiveIntegerField()),
                ('Material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.material')),
                ('Style', models.ManyToManyField(help_text='Стиль', to='catalog.Style')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Описание', max_length=1000)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Quantity', models.PositiveIntegerField()),
                ('Material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.material')),
                ('Style', models.ManyToManyField(help_text='Стиль', to='catalog.Style')),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Описание', max_length=1000)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Quantity', models.PositiveIntegerField()),
                ('Material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.material')),
                ('Style', models.ManyToManyField(help_text='Стиль', to='catalog.Style')),
            ],
        ),
    ]
