# Generated by Django 3.1.7 on 2021-03-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210314_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='Type',
            field=models.CharField(default='Посуда', max_length=200),
        ),
    ]
