# Generated by Django 3.1.7 on 2021-03-18 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
