# Generated by Django 3.1.7 on 2021-03-22 05:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210319_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decor',
            name='style',
            field=models.ManyToManyField(help_text='Стиль', to='catalog.style'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='style',
            field=models.ManyToManyField(help_text='Стиль', to='catalog.style'),
        ),
        migrations.AlterField(
            model_name='pot',
            name='style',
            field=models.ManyToManyField(help_text='Стиль', to='catalog.style'),
        ),
    ]
