# Generated by Django 3.1.7 on 2021-03-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210322_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decor',
            name='style',
            field=models.ManyToManyField(help_text='Стиль', to='catalog.style'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='style',
            field=models.ManyToManyField(help_text='Стиль', to='catalog.style'),
        ),
        migrations.AlterField(
            model_name='pot',
            name='style',
            field=models.ManyToManyField(help_text='Стиль', to='catalog.style'),
        ),
    ]
